# Generated by Django 4.2.1 on 2023-09-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255, verbose_name='First name')),
                ('sname', models.CharField(max_length=255, verbose_name='Second name')),
                ('phone', models.TextField(verbose_name='Phone number')),
                ('role', models.CharField(max_length=255, verbose_name='Role in the group')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
            },
        ),
    ]
