# Generated by Django 4.2.1 on 2023-09-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='pic',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
